apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-arng
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr712-0075-0025-tenant/tkrw-pr712-0075-0025-app/devfile-sample-arng@sha256:5070c1f5dd0ca4e9025586c1d7c05bd4acbafba8d043722b7dc6ff77b15915a3
        name: my-nodejs
        resources: {}
status: {}
